### ISSUE TITLE
Freeze issues

### ISSUE THREAD

**Issue by osztenkurden** [advancedfx/afx-cefhud-interop#9] opened 2021-05-24 09:27 UTC
CS:GO freezes after `afx_interop connect 1` if:

- [x] `backdrop-filter: contrast(50%) brightness(50%) blur(10px);` is removed from css or
- [x] `this.elClientTime.innerText = renderInfo.curTime;` is removed from `onRenderViewBegin` or
- [x] main is removed (with clientTime moved outside so it still can be filled) or
- [x] it's first connect to fresh CS:GO

**Comment by dtugend** [comment] 2021-05-24 17:54
I can only consistently reproduce this one:
- it's first connect to fresh CS:GO

The other cases work upon second connect to CS:GO after changing the HTML (the first connect after changing it still is problematic):
- `backdrop-filter: contrast(50%) brightness(50%) blur(10px);` is removed from css
![image](https://user-images.githubusercontent.com/3610128/119387281-04359180-bcc9-11eb-8a34-d019fe4093bb.png)
- `this.elClientTime.innerText = renderInfo.curTime;` is removed from `onRenderViewBegin`
![image](https://user-images.githubusercontent.com/3610128/119387449-3f37c500-bcc9-11eb-9843-58c2e89dcf12.png)
- main is removed (with clientTime moved outside so it still can be filled)

So I am concluding there's something wrong in CEF or the CS:GO HLAE AfxHookSource client end that causes it and it's not related directly to these changes (those mainly affect how fast the cefhud interop will connect, which is probably triggering / related to the bug)

**Comment by kubo6472** [comment] 2021-05-24 18:08
In a less scientific sounding way. The moment e.g. a GIF is loaded on custom embedded hud (utilizing afx cefhud interop). It freezes the CS:GO client.

**Comment by dtugend** [comment] 2021-05-24 18:21
I am guessing it happens when the CEF client releases a shared texture handle, since it notifies the main process about it, so it can notify the javascript process, so it can notify the CS:GO client, but I don't know yet.

**Comment by dtugend** [comment] 2021-06-28 21:16
@osztenkurden @kubo6472  try the new one when you have time
https://github.com/advancedfx/afx-cefhud-interop/releases/tag/v7.0.0.2-54ca6d2

**Comment by dtugend** [comment] 2021-07-03 12:26
The freeze issue with CEF 3770 boils down to blocking the GPU process and thus later the UI thread in the browser process upon second frame due to me wanting to access clear pass and render pass directly, which in turn blocks the render thread.
Now I could work around this problem alone, but there's another problem:

Apparently in 3770 (the last official CEF that works with shared textures) it does stuff like this:
1) SendExternalBeginFrame in UI Process
2) Clear 1 in GPU Process
3) Render 1 in GPU Process
4) Clear 2 in GPU Process
5) Render 2 in GPU Process
6) Pushes out share_handle_A in UI Process
7) Pushes out share_handle_A in UI Process (from same texture again)

At this point I am cosindiering to patch the latest version of CEF for shared textures + clear pass access myself, because I can not access the results of 2,3,4,5 directly in Render Process directly as I planned to do.

The critcial part is 3, since I can not access safely the result of 3 before it does 6, I have found no way yet to disable what they call "double buffering" (and with regards to shared texture content is just working not properly).
This would not be a problem with mat_queue_mode 2 and mat_qeue_mode -1 though, because there I can have a frame lingering.

**Comment by dtugend** [comment] 2021-07-03 20:20
I think I have solved most things apart from the GIF freezeing ther RENDERER process (JavaScript engine) :(

**Comment by osztenkurden** [comment] 2021-07-03 21:53
Including freeze on 404 img? 😅 I might add it to the issue if you want

**Comment by dtugend** [comment] 2021-07-04 06:41
> Including freeze on 404 img? 😅 I might add it to the issue if you want

404 image is not a problem anymore.
- It froze on first startup after rebooting PC.
- Otherwise only freezes when GIF is enabled.

**Comment by dtugend** [comment] 2021-07-05 14:27
Hi all issues but the GIFs issue is fixed, I'll track this GIFs issue a separate issue #10 since it's a CEF / Chromium bug that needs to be addressed by updating to latest, but latest doesn't have shared textures OSR, so I would need to patch it etc, not trivial.

**Closed as completed by dtugend** 2021-07-05 14:27 UTC
Labels: bug
